name: "The name of your action here"
description: "Provide a description here"
author: "Your name or organization here"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "heart"
  color: "red"

# Define your inputs here.
inputs:
  file_path:
    description: "Your input description here"
    required: true
    default: "./src/"
  config_path:
    description: "Your input description here"
    required: false
  output_path:
    description: "Your input description here"
    required: false
    default: "output.json"
  format:
    description: "Your input description here"
    required: false
    default: "table"
  json:
    description: "Your input description here"
    required: false
    default: "false"
  output_limit:
    description: "Your input description here"
    required: false
    default: "5000"
  score_cap:
    description: "Your input description here"
    required: false
    default: "1000"
  include_comments:
    description: "Your input description here"
    required: false
    default: "false"
  exclude_under:
    description: "Your input description here"
    required: false
    default: "6"
  exclude_directories:
    description: "Your input description here"
    required: false
    default: "/dist, /bin, /build"
  exclude_filenames:
    description: "Your input description here"
    required: false
    default: ".d.ts, .min.js, .bundle.js"
  extensions:
    description: "Your input description here"
    required: false
    default: ".js, .jsx, .ts, .tsx"

# Define your outputs here.
outputs:
  summary:
    description: "Your output description here"
  details:
    description: "Your output description here"

runs:
  using: node20
  main: dist/index.js
